repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
    - id: check-added-large-files
    - id: debug-statements
    - id: end-of-file-fixer
    - id: check-symlinks
    - id: trailing-whitespace
    - id: mixed-line-ending
      args: ['--fix=lf']
    - id: flake8
      additional_dependencies: [
      'flake8-blind-except',
      'flake8-commas',
      'flake8-comprehensions',
      'flake8-deprecated',
      'flake8-mutable',
      'flake8-tidy-imports',
      'flake8-print',
      ]

- repo: https://github.com/humitos/mirrors-autoflake
  rev: v1.1
  hooks:
    - id: autoflake
      args: ['--in-place', '--remove-all-unused-imports', '--remove-unused-variable']

- repo: https://github.com/asottile/seed-isort-config
  rev: v1.9.2
  hooks:
  - id: seed-isort-config
- repo: https://github.com/pre-commit/mirrors-isort
  rev: v4.3.20
  hooks:
  - id: isort

- repo: https://github.com/psf/black
  rev: 19.3b0
  hooks:
  - id: black
    files: '\.py$'
