language: python

os:
  - linux

stages:
  - lint
  - test

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "nightly"
  - "pypy3"

install:
  - pip install --upgrade pip

script: skip

jobs:
  include:
    - stage: lint
      install:
        - pip install pre-commit
        - pre-commit install-hooks
      script:
        - pre-commit run --all-files
    - stage: test
      install:
        - pip install --pre poetry
        - poetry install -v
      script:
        - poetry run pytest

after_success:
  - if [ "$TRAVIS_TAG" = "true" ] && [ "$TRAVIS_BRANCH" = "master" ]; poetry build && poetry publish -u $PYPI_USER -p $PYPI_PASSWORD; fi

cache:
  pip: true
  directories:
    - "$HOME/.cache/pre-commit"
    - .venv
